Command = require('../concepts/Command')

class Iterator extends Command
  type: 'Iterator'
  
  signature: [
  	collection: ['Query', 'Selector'],
  	body: null
  ]
  
  # Capture commands generated by css rule block
  provide: (engine, result, operation, continuation, scope, ascender) ->
    if operation.index == 1
      operation[2].command.solve engine, operation, continuation, ascending, operation
      return false

  connect: (engine, operation, continuation) ->
    return @engine.Continuation.get(continuation, null, @DESCEND)

  
Iterator.define
  # CSS rule
  
  "rule":
    index: 'rules'
    
  "each": {}
  
module.exports = Iterator