# CSS rules and conditions
compiler = require 'gss-compiler'

class Rules
  # The wonderful semicolon
  # Executes each argument with current continuations
  # - Expressions dont affect each other
  # - Unresolved values dont stop other expressions from executing

  ';':
    prefix: ''
    noop: true
    evaluate: (arg, evaluated) ->
      return arg if arg.index == 0
      if arg.index == 1 || (evaluated[1] && arg.index == 2)
        value = @evaluate arg
        value = null if value == undefined
        return value

  
  # Conditionals
  
  "$rule":
    # Set rule body scope to a found element
    evaluate: (operation, continuation, scope, ascender, ascending) ->
      if operation.index == 2 && !ascender
        @expressions.evaluate operation, continuation, ascending, undefined, undefined, operation.parent
        return
      else
        return @

    # Capture command generated by a conditional branch
    capture: (result, parent, continuation, scope) ->
      @expressions.push result

    # Active conditional branch returns value
    command: (path, condition, positive, negative) ->
      if condition
        positive
      else
        negative

  "$if":
    prefix: "@if"
    evaluate: (arg, i, evaluated) ->
      return arg if i == 0
      if i == 1 || (evaluated[1] ? i == 2 : i == 3)
        return @evaluate arg

  "$eval": (node, type = 'text/gss') ->
    if (node.type || type) == 'text/gss-ast'
      rules = JSON.parse(node.textContent ? node)
    else
      rules = compiler.compile(node.textContent ? node)
    scope = node.nodeType && node.getAttribute('scoped')? && node.parentNode || @scope
    @run rules, undefined, scope
    return
  "$load": (node, type, method = 'GET') ->
    src = node.href || node.src || node
    type ||= node.type || 'text/gss'
    xhr = new XMLHttpRequest()
    xhr.onstatechange = ->
      if xhr.readyState == 4 && xhr.status == 20
        1
    xhr.open(node.toUpperCase(), src)





module.exports = Rules